data:
  cache_dir: ./data/processed/generation
  dataset_name: recipe_nlg
  max_length: 512
  prompt_template: 'Create a recipe with these ingredients: {ingredients}


    '
  response_key: recipe
  train_split: train
  validation_split: validation
model:
  name: TinyLlama/TinyLlama-1.1B-Chat-v1.0
  save_dir: ./models/recipe_assistant
testing:
  evaluation_metrics:
  - perplexity
  - rouge
  generation_params:
    do_sample: true
    max_new_tokens: 256
    temperature: 0.7
    top_k: 50
    top_p: 0.9
  test_examples_file: data/processed/recipe_test_examples.json
training:
  batch_size: 8
  eval_steps: 500
  evaluation_strategy: steps
  fp16: true
  gradient_accumulation_steps: 4
  learning_rate: 2.0e-05
  logging_dir: ./logs/recipe_assistant
  lora:
    alpha: 64
    dropout: 0.05
    enabled: true
    r: 8
    target_modules:
    - q_proj
    - v_proj
    - k_proj
    - o_proj
  max_train_samples: 10000
  num_train_epochs: 8
  save_steps: 500
  save_total_limit: 2
  warmup_steps: 200
  weight_decay: 0.01
