# Memory-optimized Text Generation Model Configuration

# Data settings
data:
  dataset_name: "recipe_nlg"
  train_split: "train"
  validation_split: "validation"
  prompt_template: "Create a recipe with these ingredients: {ingredients}\n\n"
  response_key: "directions"
  max_length: 256  # Reduced from 512
  max_train_samples: 10000  # Limit training data
  cache_dir: "./data/processed/generation"

# Model settings
model:
  name: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  save_dir: "./models/recipe_assistant"
  load_in_8bit: true  # Use 8-bit quantization for extreme memory savings

# Training settings
training:
  batch_size: 1  # Minimum batch size
  gradient_accumulation_steps: 16  # Accumulate gradients to simulate larger batch
  num_train_epochs: 1  # Just one epoch
  learning_rate: 2.0e-5
  weight_decay: 0.01
  warmup_steps: 100
  save_steps: 500
  save_total_limit: 1
  logging_dir: "./logs/recipe_assistant"
  evaluation_strategy: "steps"
  eval_steps: 500
  fp16: true
  lora:
    enabled: true
    r: 4  # Reduced from 8
    alpha: 16
    dropout: 0.05
    target_modules: ["q_proj", "v_proj"]

# Testing settings
testing:
  test_examples_file: "data/processed/generation/test_examples.json"
  generation_params:
    max_new_tokens: 256
    temperature: 0.7
    top_p: 0.9
    top_k: 50
    do_sample: true
  evaluation_metrics:
    - perplexity
    - rouge
